language: node_js
script:
  - npm test
deploy:
  provider: heroku
  app: bcaudan-appstore-search
  on:
    all_branches: true
  api_key:
    secure: Ny9Vj20rRgyYd/N/SUtzwE5HJh0jNwTqwQ/nkYF0M9bV8PghCKbVxGPXORYW2wZQhn8YU5khUalv3Y8Fzn+IYh6dMm9F8UdLH3DCM9PeHzNhUDyw6pZYilEfuTmvdhXfrL+sTF45zYj5mMDH4ozXfGs8xMp7ftMdBoko/sAyEWwG27+YpNpFvSfp8rFuecopWl/zBg5oaEZnkmsGlNJHlxufhyXogwKv7bwrbQwUrWcpWvytdUgG8NwHtuiojr/zRnf3ARqtaSf2C7pxPBFTd2SLOO8kZMjRJvx5Qq0AVF7XdTim19uJP4ufrZ/8RuGfpgzClxtaBNYH8Je4SmsS8Axdyw/oeidnRt8JoUgpteeFKoxHC4/cVCdKhQ4CHEYNsieH4Mm+1tGF6ekTsLb7dzZuyXIlGKquPmEwBWrQFiaKHXuNArOmUj5G06+9PlCraKv9eyXFfM4I31owRuzgWzpu2J9601du38Yh+g/5S/vXE8V7oPqwa2hG9BRaurdBIsXSyL2TFM6JmW59sa6xQLPcf6agyZTyzuuxjl+kzopBxovaWX1UplYS2yECcrNNFsxDsFz3/ZneYypBbSQXXsb61v+fhjUe5mKr2OHb55ReVLJgJqjqTBFtLUGTMx1Cgive2/tM/VBPWHy1OYudhumO9eERxFAPRuodyJu9G+s=
